minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
trustLockfile: false

trustPolicyExclude:
  - "tailwind-merge@2.6.1"

allowBuilds:
  protobufjs: true
  unrs-resolver: true
